version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Porta per accedere alla console di management
      - "5672:5672"   # Porta per connessioni client e comunicazione tra servizi
    networks:
      - apigateway_net
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-rabbitmq
        target: /var/lib/rabbitmq

  gateway:
    container_name: apigateway
    build: ./apigateway
    image: dipada/apigateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - '30085:8085'
    depends_on:
      - discovery-server
      - userservice
      - authenticationservice
      - shopservice
      - productservice
    networks:
      - apigateway_net

  discovery-server:
    container_name: discoveryserver
    build: ./discoveryserver
    image: dipada/discoveryserver
    ports:
      - '8761:8761'
    networks:
      - apigateway_net

  userservice:
    build: ./userservice
    image: dipada/userservice
    container_name: userservice
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - discovery-server
      - rabbitmq
      - authenticationservice
    networks:
      - userservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sdglocaldelights
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  postgres:
    container_name: postgres_container_userservice
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdglocaldelights
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - userservice
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - userservice
      - shopservice
      - productservice

  authenticationservice:
    build: ./authenticationservice
    image: dipada/authenticationservice
    container_name: authenticationservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
    ports:
      - '30080:8080'
    depends_on:
      - discovery-server
      - rabbitmq
    networks:
      - authenticationservice
      - apigateway_net


  shopservice:
    build: ./shopservice
    image: dipada/shopservice
    container_name: shopservice
    ports:
      - '8082:8082'
    depends_on:
      - postgres-shop
      - discovery-server
      - rabbitmq
    networks:
      - shopservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-shop:5432/sdgshops
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  postgres-shop:
    container_name: postgres_container_shopservice
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdgshops
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5433:5432'
    volumes:
      - shop-db-data:/var/lib/postgresql/data
    networks:
      - shopservice
    restart: unless-stopped

  productservice:
    build: ./productservice
    image: dipada/productservice
    container_name: productservice
    ports:
      - '8083:8083'
    depends_on:
      - postgres-product
      - discovery-server
      - rabbitmq
      - shopservice
    networks:
      - productservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-product:5432/sdgproducts
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672


  postgres-product:
    container_name: postgres_container_product
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdgproducts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5439:5432'
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - productservice
    restart: unless-stopped


  postgres-payment:
    container_name: paymentservice_container
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdgpayments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5435:5432'
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - paymentservice_net
    restart: unless-stopped

  paymentservice:
    build: ./paymentservice
    image: dipada/paymentservice
    container_name: paymentservice
    ports:
      - '8084:8084'
    depends_on:
      - postgres-payment
      - discovery-server
      - rabbitmq
    networks:
      - paymentservice_net
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5432/sdgpayments
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  postgres-order:
    container_name: postgres_container_orderservice
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdgorders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5436:5432'
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    networks:
      - order_net
    restart: unless-stopped

  orderservice:
    build: ./orderservice
    image: dipada/orderservice
    container_name: orderservice
    ports:
      - '8086:8086'
    depends_on:
      - postgres
      - discovery-server
      - rabbitmq
    networks:
      - order_net
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5432/sdgorders
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  frontend:
    container_name: frontend
    build: ./frontend
    image: dipada/frontend
    ports:
      - '30073:5173'

volumes:
  db-data:
  pgadmin-data:
  shop-db-data:
  product-db-data:
  data-rabbitmq:
  payment-db-data:
  orders-db-data:


networks:
  userservice:
    driver: bridge
  authenticationservice:
    driver: bridge
  apigateway_net:
    driver: bridge
  shopservice:
    driver: bridge
  productservice:
    driver: bridge
  paymentservice_net:
    driver: bridge
  order_net:
    driver: bridge