version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Porta per accedere alla console di management
      - "5672:5672"   # Porta per connessioni client e comunicazione tra servizi
    networks:
      - apigateway_net
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-rabbitmq
        target: /var/lib/rabbitmq

  gateway:
    container_name: apigateway
    build: ./apigateway
    image: apigateway
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - '8085:8085'
    depends_on:
      - discovery-server
      - userservice
      - authenticationservice
      - shopservice
      - productservice
    networks:
      - apigateway_net

  discovery-server:
    container_name: discoveryserver
    build: ./discoveryserver
    image: discoveryserver
    ports:
      - '8761:8761'
    networks:
      - apigateway_net

  userservice:
    build: ./userservice
    image: userservice
    container_name: userservice
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - discovery-server
    networks:
      - userservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sdglocaldelights
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker

  postgres:
    container_name: postgres_container_userservice
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdglocaldelights
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - userservice
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - userservice
      - shopservice
      - productservice

  authenticationservice:
    build: ./authenticationservice
    image: authenticationservice
    container_name: authenticationservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
    ports:
      - '8080:8080'
    depends_on:
      - discovery-server
    networks:
      - authenticationservice
      - apigateway_net

  shopservice:
    build: ./shopservice
    image: shopservice
    container_name: shopservice
    ports:
      - '8082:8082'
    depends_on:
      - postgres_shop
      - discovery-server
      - rabbitmq
    networks:
      - shopservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_shop:5432/sdgshops
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  postgres_shop:
    container_name: postgres_container_shopservice
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdgshops
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5433:5432'
    volumes:
      - shop-db-data:/var/lib/postgresql/data
    networks:
      - shopservice
    restart: unless-stopped

  productservice:
    build: ./productservice
    image: productservice
    container_name: productservice_container
    ports:
      - '8083:8083'
    depends_on:
      - postgres_product
      - discovery-server
      - rabbitmq
      - shopservice
    networks:
      - productservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_product:5432/sdgproducts
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672


  postgres_product:
    container_name: postgres_container_product
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdgproducts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5439:5432'
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - productservice
    restart: unless-stopped


volumes:
  db-data:
  pgadmin-data:
  shop-db-data:
  product-db-data:
  data-rabbitmq:


networks:
  userservice:
    driver: bridge
  authenticationservice:
    driver: bridge
  apigateway_net:
    driver: bridge
  shopservice:
    driver: bridge
  productservice:
    driver: bridge