version: '3'

services:
  gateway:
    container_name: apigateway
    build: ./apigateway
    image: apigateway
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - '8085:8085'
    depends_on:
      - discovery-server
      - userservice
      - authenticationservice
    networks:
      - apigateway_net

  discovery-server:
    container_name: discoveryserver
    build: ./discoveryserver
    image: discoveryserver
    ports:
      - '8761:8761'
    networks:
      - apigateway_net

  userservice:
    build: ./userservice
    image: userservice
    container_name: userservice
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - discovery-server
    networks:
      - userservice
      - apigateway_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sdglocaldelights
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
  postgres:
    container_name: postgres_container_userservice
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdglocaldelights
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - userservice
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - userservice

  authenticationservice:
    build: ./authenticationservice
    image: authenticationservice
    container_name: authenticationservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
    ports:
      - '8080:8080'
    depends_on:
      - discovery-server
    networks:
      - authenticationservice
      - apigateway_net

volumes:
  db-data:
  pgadmin-data:
networks:
  userservice:
    driver: bridge
  authenticationservice:
    driver: bridge
  apigateway_net:
    driver: bridge