server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true

spring:
  application:
    api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
