server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: http://userservice:8081
          predicates:
            - Path=/api/v1/user/**
        - id: authenticationservice
          uri: http://authenticationservice:8080
          predicates:
            - Path=/auth/**
        - id: shopservice
          uri: http://shopservice:8082
          predicates:
            - Path=/shop/**
        - id: paymentservice
          uri: http://paymentservice:8084
          predicates:
            - Path=/payment/**
        - id: productservice
          uri: http://productservice:8083
          predicates:
            - Path=/product/**
        - id: orderservice
          uri: http://orderservice:8086
          predicates:
            - Path=/api/v1/order/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: false
            maxAge: 3600