server:
  port: 8084

spring:
  application:
    name: paymentservice

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true