server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/v1/user/**
        - id: authenticationservice
          uri: lb://authenticationservice
          predicates:
            - Path=/auth/**