spring:
  application:
    name: orderservice
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: order.exchange
    queue: order.queue
    routingkey: order.routingkey
server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    refresh:
      enable: true
