version: '3'

services:
  postgres:
    container_name: postgres_container_user
    image: 'postgres:latest'
    hostname: localhost
    environment:
      POSTGRES_DB: sdglocaldelights
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - userservice
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - userservice

  userservice:
    build: .
    image: userservice
    container_name: userservice_container
    ports:
      - '8081:8081'
    depends_on:
        - postgres
    networks:
        - userservice
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sdglocaldelights
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db-data:
  pgadmin-data:
networks:
  userservice:
    driver: bridge